name: crispac_logistics
description: "Crispac Logistics Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  intl: ^0.18.1
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: 5.0.0

# --- FLUTTER LAUNCHER ICONS CONFIG (ROOT LEVEL, NOT UNDER FLUTTER) ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/hotel.png
    - assets/med.png
    - assets/regi.png
    - assets/school.png
    - assets/industrial.jpg
    - assets/forgot_password.png
    - assets/Custom Designs.png
    - assets/Corporate Suit.png
    - assets/Chef Coat.jpg
    - assets/Construction Wear.png
    - assets/Hospital Gown.png
    - assets/School Uniform.png


  # cupertino_icons: ^1.0.8